name: peopnet
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  http: ^1.4.0
  fpdart: ^1.1.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5
  shared_preferences: ^2.5.3
  file_picker: ^10.1.9
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/img/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-VariableFont_wght.ttf

    - family: Lexendbold
      fonts:
        - asset: assets/font/Lexend-Bold.ttf

    - family: Lexendthin
      fonts:
        - asset: assets/font/Lexend-Thin.ttf

    - family: Lexendregular
      fonts:
        - asset: assets/font/Lexend-Regular.ttf